resources:
  - device-class.yaml
  - namespace.yaml
  - resource-driver.yaml

#images:
#  - name: ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gaudi-resource-driver
#    newName: registry.local/intel-gaudi-resource-driver
#    newTag: v0.6.0
