resources:
  - device-class.yaml
  - namespace.yaml
  - resource-driver.yaml

#images:
#  - name: ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver
#    newName: ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver
#    newTag: v0.9.0
