{{- if .Values.openshift.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:{{ .Values.openshift.sccName }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ .Values.openshift.sccName }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}
